TARGET=rt_lpc
OBJS=lpc.o rt_lpc.o RtAudio.o Thread.o Stk.o chuck_fft.o midiio_alsa.o

CC=gcc
CPP=g++
INCLUDES=
CFLAGS=-D__LINUX_OSS__ $(INCLUDES) -O3 -c
LIBS=-lasound -lpthread -L/usr/X11R6/lib -lGL -lGLU -lglut -lX11 -lXi -lXext -lXmu -lm

rt_lpc: $(OBJS)
	$(CPP) -o $@ $(OBJS) $(LIBS)

.o: $*.h

.c.o: $*.h $*.c
	$(CC) $(CFLAGS) $*.c

.cpp.o: $*.h $*.cpp
	$(CC) $(CFLAGS) $*.cpp

clean: 
	rm -f rt_lpc *~ *.o
