TARGET=rt_lpc
OBJS=lpc.o rt_lpc.o RtAudio.o Thread.o Stk.o chuck_fft.o midiio_win32.o

CC=gcc
CPP=g++
INCLUDES=-I/usr/include/directx/
CFLAGS=-D__WINDOWS_DS__ -D__WINDOWS_PTHREAD__ $(INCLUDES) -O3 -g -c
LIBS=-ldsound -ldxguid -lwinmm -lpthread -lopengl32 -lglu32 -lglut32

rt_lpc: $(OBJS)
	$(CPP) -o $@ $(OBJS) $(LIBS)

.o: $*.h

.c.o: $*.h $*.c
	$(CC) $(CFLAGS) $*.c

.cpp.o: $*.h $*.cpp
	$(CC) $(CFLAGS) $*.cpp

clean: 
	rm -f rt_lpc.exe *~ *.o
